name       : perl-common-sense
version    : '3.75'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/common-sense-3.75.tar.gz : a86a1c4ca4f3006d7479064425a09fa5b6689e57261fcb994fe67d061cba0e7e
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : common::sense - save a tree AND a kitten, use common::sense!
description: |
    This module implements some sane defaults for Perl programs, as defined by two typical (or not so typical - use your common sense) specimens of Perl coders. In fact, after working out details on which warnings and strict modes to enable and make fatal, we found that we (and our code written so far, and others) fully agree on every option, even though we never used warnings before, so it seems this module indeed reflects a "common" sense among some long-time Perl coders.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
